// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace VSTS.SampleData.UI_Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Startbrowser - Test Case 11737
        /// </summary>
        public void Startbrowser()
        {
            #region Variable Declarations
            WinButton uIOverviewVisualStudioButton = this.UIRunningapplicationsWindow.UIRunningapplicationsToolBar.UIOverviewVisualStudioButton;
            WinClient uIJumpListClient = this.UIJumpListWindow.UIItemWindow.UIJumpListClient;
            #endregion

            BrowserWindow browser = BrowserWindow.Launch(new System.Uri("https://almrangers-sandbox-one.visualstudio.com/DefaultCollection/SampleDataTest1/"));

        }
        
        /// <summary>
        /// Navigatetoproject - Test Case 11737 - Use 'NavigatetoprojectParams' to pass parameters into this method.
        /// </summary>
        public void Navigatetoproject()
        {
            #region Variable Declarations
            WinMenuItem uIItemMenuItem = this.UISecuritySettingsatRiWindow.UIAddressComboControlToolBar.UIItemMenuItem;
            BrowserWindow uISecuritySettingsatRiWindow = this.UISecuritySettingsatRiWindow;
            #endregion

            // Click menu item numbered 2 in 'Address Combo Control' menu item
            Mouse.Click(uIItemMenuItem, new Point(41, 20));

            // Go to web page 'https://almrangers-sandbox-one.visualstudio.com/DefaultCollection/SampleDataTest1/'
            uISecuritySettingsatRiWindow.NavigateToUrl(new System.Uri(this.NavigatetoprojectParams.UISecuritySettingsatRiWindowUrl));
        }
        
        /// <summary>
        /// SelectStarWarstemplate - Test Case 11737 - Use 'SelectStarWarstemplateParams' to pass parameters into this method.
        /// </summary>
        public void SelectStarWarstemplate()
        {
            #region Variable Declarations
            HtmlSpan uIItemPane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIHeaderrowPane.UIItemPane;
            HtmlCustom uIMi_14Custom = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIMi_14Custom;
            HtmlDiv uIManageprojectPane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIMi_14Custom.UIManageprojectPane;
            HtmlCustom uIMi_17Custom = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIMi_17Custom;
            BrowserWindow uIOverviewVisualStudioWindow = this.UIOverviewVisualStudioWindow;
            HtmlHyperlink uIWorkinProgress0WorkiHyperlink = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIWorkinProgress0WorkiPane.UIWorkinProgress0WorkiHyperlink;
            HtmlEdit uIBugEdit = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem99Pane.UIBugEdit;
            HtmlDiv uIQueryreturnednoresulPane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem94Pane.UIQueryreturnednoresulPane;
            HtmlDiv uIWelcomeGetstartedusiPane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIWidgetscontainerPane.UIWelcomeGetstartedusiPane;
            HtmlDiv uIItemPane1 = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIExternalContentHost8Frame.UISampleDataWidgetDocument.UIItem1Pane.UIItemPane;
            HtmlCustom uIStarWarsCustom = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIExternalContentHost8Frame.UISampleDataWidgetDocument.UIStarWarsAnishaDesignPane.UIStarWarsCustom;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            

            // Maximize window 'Overview - Visual Studio Team Services - Internet ...'
            uIOverviewVisualStudioWindow.Maximized = this.SelectStarWarstemplateParams.UIOverviewVisualStudioWindowMaximized;

         
            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;


            // Click pane
            Mouse.Click(uIItemPane1, new Point(10, 11));

            uIStarWarsCustom.WaitForControlExist();

            // Click 'StarWars' custom control
            Mouse.Click(uIStarWarsCustom, new Point(231, 13));
        }
        
        /// <summary>
        /// ClickPopulate - Test Case 11737
        /// </summary>
        public void ClickPopulate()
        {
            #region Variable Declarations
            HtmlDiv uIQueryreturnednoresulPane1 = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem94Pane.UIQueryreturnednoresulPane1;
            HtmlDiv uIWelcomeGetstartedusiPane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIWidgetscontainerPane.UIWelcomeGetstartedusiPane;
            HtmlInputButton uIPopulateButton = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIExternalContentHost8Frame.UISampleDataWidgetDocument.UIPopulateButton;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Query returned no results. Create new wo' pane at (1, 1)
            Mouse.Hover(uIQueryreturnednoresulPane1, new Point(1, 1));

            // Mouse hover 'Welcome Get started using Visual Stud' pane at (1, 1)
            Mouse.Hover(uIWelcomeGetstartedusiPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Populate' button
            Mouse.Click(uIPopulateButton, new Point(51, 17));
        }
        
        /// <summary>
        /// Wait - Test Case 11737
        /// </summary>
        public void Wait()
        {
            #region Variable Declarations
            HtmlDiv uIQueryreturnednoresulPane1 = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem94Pane.UIQueryreturnednoresulPane1;
            HtmlImage uI_statictfs20160204T1Image = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem94Pane.UI_statictfs20160204T1Image;
            HtmlDiv uIItem92Pane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem92Pane;
            HtmlImage uIIconsjonathanreystarImage = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIExternalContentHost8Frame.UISampleDataWidgetDocument.UIIconsjonathanreystarImage;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Query returned no results. Create new wo' pane at (1, 1)
            Mouse.Hover(uIQueryreturnednoresulPane1, new Point(1, 1));

            // Mouse hover '/_static/tfs/20160204T180102/_content/chart-noresu...' image at (1, 1)
            Mouse.Hover(uI_statictfs20160204T1Image, new Point(1, 1));

            // Mouse hover '92' pane at (1, 1)
            Mouse.Hover(uIItem92Pane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click '/icons/jonathan-rey/star-wars-characters/64/Yoda-0...' image
            Mouse.Click(uIIconsjonathanreystarImage, new Point(35, 45));
        }
        
        /// <summary>
        /// ClickRemove - Test Case 11737
        /// </summary>
        public void ClickRemove()
        {
            #region Variable Declarations
            HtmlDiv uIQueryreturnednoresulPane1 = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem94Pane.UIQueryreturnednoresulPane1;
            HtmlDiv uIWelcomeGetstartedusiPane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIWidgetscontainerPane.UIWelcomeGetstartedusiPane;
            HtmlInputButton uIDeleteButton = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIExternalContentHost8Frame.UISampleDataWidgetDocument.UIDeleteButton;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Query returned no results. Create new wo' pane at (1, 1)
            Mouse.Hover(uIQueryreturnednoresulPane1, new Point(1, 1));

            // Mouse hover 'Welcome Get started using Visual Stud' pane at (1, 1)
            Mouse.Hover(uIWelcomeGetstartedusiPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Delete' button
            Mouse.Click(uIDeleteButton, new Point(43, 15));
        }
        
        /// <summary>
        /// Wait1 - Test Case 11737
        /// </summary>
        public void Wait1()
        {
            #region Variable Declarations
            HtmlDiv uIQueryreturnednoresulPane1 = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem94Pane.UIQueryreturnednoresulPane1;
            HtmlDiv uIWelcomeGetstartedusiPane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIWidgetscontainerPane.UIWelcomeGetstartedusiPane;
            HtmlDiv uIWorkItemSampleDataSePane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIExternalContentHost8Frame.UISampleDataWidgetDocument.UIProgressBarPane.UIWorkItemSampleDataSePane;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Query returned no results. Create new wo' pane at (1, 1)
            Mouse.Hover(uIQueryreturnednoresulPane1, new Point(1, 1));

            // Mouse hover 'Welcome Get started using Visual Stud' pane at (1, 1)
            Mouse.Hover(uIWelcomeGetstartedusiPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'WorkItemSampleDataServiceTFS.WebApi.Exception: TF4...' pane
            Mouse.Click(uIWorkItemSampleDataSePane, new Point(21, 10));
        }
        
        /// <summary>
        /// Item - Test Case 11737
        /// </summary>
        public void CloseBrowser()
        {
            #region Variable Declarations
            HtmlImage uI_statictfs20160204T1Image = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem94Pane.UI_statictfs20160204T1Image;
            HtmlHyperlink uIContinuouslyintegratHyperlink = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem97Pane.UIContinuouslyintegratHyperlink;
            HtmlDiv uIQueryreturnednoresulPane1 = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UIItem94Pane.UIQueryreturnednoresulPane1;
            HtmlDiv uICf83dffaafcf43f09b40Pane = this.UIOverviewVisualStudioWindow.UIOverviewVisualStudioDocument.UICf83dffaafcf43f09b40Pane;
            BrowserWindow uIOverviewVisualStudioWindow = this.UIOverviewVisualStudioWindow;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/_static/tfs/20160204T180102/_content/chart-noresu...' image at (1, 1)
            Mouse.Hover(uI_statictfs20160204T1Image, new Point(1, 1));

            // Mouse hover 'Continuously integrate Automate your builds' link at (1, 1)
            Mouse.Hover(uIContinuouslyintegratHyperlink, new Point(1, 1));

            // Mouse hover 'Query returned no results. Create new wo' pane at (1, 1)
            Mouse.Hover(uIQueryreturnednoresulPane1, new Point(1, 1));

            // Mouse hover 'cf83dffa-afcf-43f0-9b40-82ac7a4e652e' pane at (1, 1)
            Mouse.Hover(uICf83dffaafcf43f09b40Pane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Perform Close on Browser Window
            uIOverviewVisualStudioWindow.Close();
        }
        
        #region Properties
        public virtual NavigatetoprojectParams NavigatetoprojectParams
        {
            get
            {
                if ((this.mNavigatetoprojectParams == null))
                {
                    this.mNavigatetoprojectParams = new NavigatetoprojectParams();
                }
                return this.mNavigatetoprojectParams;
            }
        }
        
        public virtual SelectStarWarstemplateParams SelectStarWarstemplateParams
        {
            get
            {
                if ((this.mSelectStarWarstemplateParams == null))
                {
                    this.mSelectStarWarstemplateParams = new SelectStarWarstemplateParams();
                }
                return this.mSelectStarWarstemplateParams;
            }
        }
        
        public UIRunningapplicationsWindow UIRunningapplicationsWindow
        {
            get
            {
                if ((this.mUIRunningapplicationsWindow == null))
                {
                    this.mUIRunningapplicationsWindow = new UIRunningapplicationsWindow();
                }
                return this.mUIRunningapplicationsWindow;
            }
        }
        
        public UIJumpListWindow UIJumpListWindow
        {
            get
            {
                if ((this.mUIJumpListWindow == null))
                {
                    this.mUIJumpListWindow = new UIJumpListWindow();
                }
                return this.mUIJumpListWindow;
            }
        }
        
        public UISecuritySettingsatRiWindow UISecuritySettingsatRiWindow
        {
            get
            {
                if ((this.mUISecuritySettingsatRiWindow == null))
                {
                    this.mUISecuritySettingsatRiWindow = new UISecuritySettingsatRiWindow();
                }
                return this.mUISecuritySettingsatRiWindow;
            }
        }
        
        public UIOverviewVisualStudioWindow UIOverviewVisualStudioWindow
        {
            get
            {
                if ((this.mUIOverviewVisualStudioWindow == null))
                {
                    this.mUIOverviewVisualStudioWindow = new UIOverviewVisualStudioWindow();
                }
                return this.mUIOverviewVisualStudioWindow;
            }
        }
        #endregion
        
        #region Fields
        private NavigatetoprojectParams mNavigatetoprojectParams;
        
        private SelectStarWarstemplateParams mSelectStarWarstemplateParams;
        
        private UIRunningapplicationsWindow mUIRunningapplicationsWindow;
        
        private UIJumpListWindow mUIJumpListWindow;
        
        private UISecuritySettingsatRiWindow mUISecuritySettingsatRiWindow;
        
        private UIOverviewVisualStudioWindow mUIOverviewVisualStudioWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Navigatetoproject'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class NavigatetoprojectParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://almrangers-sandbox-one.visualstudio.com/DefaultCollection/SampleDataTest1/'
        /// </summary>
        public string UISecuritySettingsatRiWindowUrl = "https://almrangers-sandbox-one.visualstudio.com/DefaultCollection/SampleDataTest1" +
            "/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SelectStarWarstemplate'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SelectStarWarstemplateParams
    {
        
        #region Fields
        /// <summary>
        /// Maximize window 'Overview - Visual Studio Team Services - Internet ...'
        /// </summary>
        public bool UIOverviewVisualStudioWindowMaximized = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRunningapplicationsWindow : WinWindow
    {
        
        public UIRunningapplicationsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Running applications";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSTaskSwWClass";
            this.WindowTitles.Add("Running applications");
            #endregion
        }
        
        #region Properties
        public UIRunningapplicationsToolBar UIRunningapplicationsToolBar
        {
            get
            {
                if ((this.mUIRunningapplicationsToolBar == null))
                {
                    this.mUIRunningapplicationsToolBar = new UIRunningapplicationsToolBar(this);
                }
                return this.mUIRunningapplicationsToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIRunningapplicationsToolBar mUIRunningapplicationsToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRunningapplicationsToolBar : WinToolBar
    {
        
        public UIRunningapplicationsToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Running applications";
            this.WindowTitles.Add("Running applications");
            #endregion
        }
        
        #region Properties
        public WinButton UIOverviewVisualStudioButton
        {
            get
            {
                if ((this.mUIOverviewVisualStudioButton == null))
                {
                    this.mUIOverviewVisualStudioButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOverviewVisualStudioButton.SearchProperties[WinButton.PropertyNames.Name] = "Overview - Visual Studio Team Services - Internet Explorer";
                    this.mUIOverviewVisualStudioButton.WindowTitles.Add("Running applications");
                    #endregion
                }
                return this.mUIOverviewVisualStudioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOverviewVisualStudioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIJumpListWindow : WinWindow
    {
        
        public UIJumpListWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Jump List";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DV2ControlHost";
            this.WindowTitles.Add("Jump List");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DesktopDestinationList";
            this.WindowTitles.Add("Jump List");
            #endregion
        }
        
        #region Properties
        public WinClient UIJumpListClient
        {
            get
            {
                if ((this.mUIJumpListClient == null))
                {
                    this.mUIJumpListClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIJumpListClient.WindowTitles.Add("Jump List");
                    #endregion
                }
                return this.mUIJumpListClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIJumpListClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISecuritySettingsatRiWindow : BrowserWindow
    {
        
        public UISecuritySettingsatRiWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Security Settings at Risk";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Security Settings at Risk");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressComboControlToolBar UIAddressComboControlToolBar
        {
            get
            {
                if ((this.mUIAddressComboControlToolBar == null))
                {
                    this.mUIAddressComboControlToolBar = new UIAddressComboControlToolBar(this);
                }
                return this.mUIAddressComboControlToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressComboControlToolBar mUIAddressComboControlToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddressComboControlToolBar : WinToolBar
    {
        
        public UIAddressComboControlToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Address Combo Control";
            this.WindowTitles.Add("Security Settings at Risk");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIItemMenuItem
        {
            get
            {
                if ((this.mUIItemMenuItem == null))
                {
                    this.mUIItemMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIItemMenuItem.SearchProperties[WinMenuItem.PropertyNames.Instance] = "2";
                    this.mUIItemMenuItem.WindowTitles.Add("Security Settings at Risk");
                    #endregion
                }
                return this.mUIItemMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIItemMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOverviewVisualStudioWindow : BrowserWindow
    {
        
        public UIOverviewVisualStudioWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Overview - Visual Studio Team Services";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIOverviewVisualStudioDocument UIOverviewVisualStudioDocument
        {
            get
            {
                if ((this.mUIOverviewVisualStudioDocument == null))
                {
                    this.mUIOverviewVisualStudioDocument = new UIOverviewVisualStudioDocument(this);
                }
                return this.mUIOverviewVisualStudioDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIOverviewVisualStudioDocument mUIOverviewVisualStudioDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOverviewVisualStudioDocument : HtmlDocument
    {
        
        public UIOverviewVisualStudioDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Overview - Visual Studio Team Services";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/DefaultCollection/SampleDataTest1/_dashboards";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://almrangers-sandbox-one.visualstudio.com/DefaultCollection/SampleDataTest1" +
                "/_dashboards";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public UIHeaderrowPane UIHeaderrowPane
        {
            get
            {
                if ((this.mUIHeaderrowPane == null))
                {
                    this.mUIHeaderrowPane = new UIHeaderrowPane(this);
                }
                return this.mUIHeaderrowPane;
            }
        }
        
        public UIMi_14Custom UIMi_14Custom
        {
            get
            {
                if ((this.mUIMi_14Custom == null))
                {
                    this.mUIMi_14Custom = new UIMi_14Custom(this);
                }
                return this.mUIMi_14Custom;
            }
        }
        
        public HtmlCustom UIMi_17Custom
        {
            get
            {
                if ((this.mUIMi_17Custom == null))
                {
                    this.mUIMi_17Custom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIMi_17Custom.SearchProperties["TagName"] = "LI";
                    this.mUIMi_17Custom.SearchProperties["Id"] = "mi_17";
                    this.mUIMi_17Custom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIMi_17Custom.FilterProperties["Class"] = "menu-item";
                    this.mUIMi_17Custom.FilterProperties["ControlDefinition"] = "class=\"menu-item\" id=\"mi_17\" role=\"menui";
                    this.mUIMi_17Custom.FilterProperties["InnerText"] = null;
                    this.mUIMi_17Custom.FilterProperties["TagInstance"] = "9";
                    this.mUIMi_17Custom.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIMi_17Custom;
            }
        }
        
        public UIWorkinProgress0WorkiPane UIWorkinProgress0WorkiPane
        {
            get
            {
                if ((this.mUIWorkinProgress0WorkiPane == null))
                {
                    this.mUIWorkinProgress0WorkiPane = new UIWorkinProgress0WorkiPane(this);
                }
                return this.mUIWorkinProgress0WorkiPane;
            }
        }
        
        public UIItem99Pane UIItem99Pane
        {
            get
            {
                if ((this.mUIItem99Pane == null))
                {
                    this.mUIItem99Pane = new UIItem99Pane(this);
                }
                return this.mUIItem99Pane;
            }
        }
        
        public UIItem94Pane UIItem94Pane
        {
            get
            {
                if ((this.mUIItem94Pane == null))
                {
                    this.mUIItem94Pane = new UIItem94Pane(this);
                }
                return this.mUIItem94Pane;
            }
        }
        
        public UIWidgetscontainerPane UIWidgetscontainerPane
        {
            get
            {
                if ((this.mUIWidgetscontainerPane == null))
                {
                    this.mUIWidgetscontainerPane = new UIWidgetscontainerPane(this);
                }
                return this.mUIWidgetscontainerPane;
            }
        }
        
        public UIExternalContentHost8Frame UIExternalContentHost8Frame
        {
            get
            {
                if ((this.mUIExternalContentHost8Frame == null))
                {
                    this.mUIExternalContentHost8Frame = new UIExternalContentHost8Frame(this);
                }
                return this.mUIExternalContentHost8Frame;
            }
        }
        
        public HtmlDiv UIItem92Pane
        {
            get
            {
                if ((this.mUIItem92Pane == null))
                {
                    this.mUIItem92Pane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItem92Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = "92";
                    this.mUIItem92Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItem92Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Visual Studio\r\n\r\nOpen in Visual Studio\r\n";
                    this.mUIItem92Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItem92Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "visual-studio-links";
                    this.mUIItem92Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"visual-studio-links\" id=\"92\"";
                    this.mUIItem92Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "142";
                    this.mUIItem92Pane.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIItem92Pane;
            }
        }
        
        public UIItem97Pane UIItem97Pane
        {
            get
            {
                if ((this.mUIItem97Pane == null))
                {
                    this.mUIItem97Pane = new UIItem97Pane(this);
                }
                return this.mUIItem97Pane;
            }
        }
        
        public HtmlDiv UICf83dffaafcf43f09b40Pane
        {
            get
            {
                if ((this.mUICf83dffaafcf43f09b40Pane == null))
                {
                    this.mUICf83dffaafcf43f09b40Pane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUICf83dffaafcf43f09b40Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = "cf83dffa-afcf-43f0-9b40-82ac7a4e652e";
                    this.mUICf83dffaafcf43f09b40Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICf83dffaafcf43f09b40Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Welcome\r\n\r\nGet started using Visual Stud";
                    this.mUICf83dffaafcf43f09b40Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICf83dffaafcf43f09b40Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUICf83dffaafcf43f09b40Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"cf83dffa-afcf-43f0-9b40-82ac7a4e652e\"";
                    this.mUICf83dffaafcf43f09b40Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "54";
                    this.mUICf83dffaafcf43f09b40Pane.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUICf83dffaafcf43f09b40Pane;
            }
        }
        #endregion
        
        #region Fields
        private UIHeaderrowPane mUIHeaderrowPane;
        
        private UIMi_14Custom mUIMi_14Custom;
        
        private HtmlCustom mUIMi_17Custom;
        
        private UIWorkinProgress0WorkiPane mUIWorkinProgress0WorkiPane;
        
        private UIItem99Pane mUIItem99Pane;
        
        private UIItem94Pane mUIItem94Pane;
        
        private UIWidgetscontainerPane mUIWidgetscontainerPane;
        
        private UIExternalContentHost8Frame mUIExternalContentHost8Frame;
        
        private HtmlDiv mUIItem92Pane;
        
        private UIItem97Pane mUIItem97Pane;
        
        private HtmlDiv mUICf83dffaafcf43f09b40Pane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHeaderrowPane : HtmlDiv
    {
        
        public UIHeaderrowPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "header-row";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Visual Studio Team Services  / SampleDat";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "nav-separated";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"nav-separated\" id=\"header-row\" role=\"banner\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "|";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "vertical-bar";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"vertical-bar\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "6";
                    this.mUIItemPane.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMi_14Custom : HtmlCustom
    {
        
        public UIMi_14Custom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "mi_14";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item\" id=\"mi_14\" role=\"menui";
            this.FilterProperties["InnerText"] = null;
            this.FilterProperties["TagInstance"] = "7";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIManageprojectPane
        {
            get
            {
                if ((this.mUIManageprojectPane == null))
                {
                    this.mUIManageprojectPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIManageprojectPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIManageprojectPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIManageprojectPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIManageprojectPane.FilterProperties[HtmlDiv.PropertyNames.Title] = "Manage project";
                    this.mUIManageprojectPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "bowtie-icon bowtie-settings-gear icon";
                    this.mUIManageprojectPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "title=\"Manage project\" class=\"bowtie-icon bowtie-settings-gear icon\"";
                    this.mUIManageprojectPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "13";
                    this.mUIManageprojectPane.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIManageprojectPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIManageprojectPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWorkinProgress0WorkiPane : HtmlDiv
    {
        
        public UIWorkinProgress0WorkiPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "109";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Work in Progress\r\n\r\n0\r\n\r\nWork items";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "count-control";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"count-control\" id=\"109\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "176";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIWorkinProgress0WorkiHyperlink
        {
            get
            {
                if ((this.mUIWorkinProgress0WorkiHyperlink == null))
                {
                    this.mUIWorkinProgress0WorkiHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIWorkinProgress0WorkiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIWorkinProgress0WorkiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIWorkinProgress0WorkiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIWorkinProgress0WorkiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Work in Progress\r\n\r\n0\r\n\r\nWork items";
                    this.mUIWorkinProgress0WorkiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIWorkinProgress0WorkiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIWorkinProgress0WorkiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "/DefaultCollection/SampleDataTest1/_workItems/resultsById/7c34a77c-74d3-4d6b-afa4" +
                        "-39fdc94db3cf";
                    this.mUIWorkinProgress0WorkiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIWorkinProgress0WorkiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/DefaultCollection/SampleDataTest1";
                    this.mUIWorkinProgress0WorkiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIWorkinProgress0WorkiHyperlink.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIWorkinProgress0WorkiHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIWorkinProgress0WorkiHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem99Pane : HtmlDiv
    {
        
        public UIItem99Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "99";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "combo input-text-box new-work-item-type list drop";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"combo input-text-box new-work-item-type list drop\" id=\"99\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "165";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIBugEdit
        {
            get
            {
                if ((this.mUIBugEdit == null))
                {
                    this.mUIBugEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIBugEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIBugEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIBugEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIBugEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIBugEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Bug";
                    this.mUIBugEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "new-work-item-type-input";
                    this.mUIBugEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "title=\"Bug\" class=\"new-work-item-type-in";
                    this.mUIBugEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIBugEdit.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIBugEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIBugEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem94Pane : HtmlDiv
    {
        
        public UIItem94Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "94";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Work in Progress \r\n\r\n\r\n\r\n\r\n\r\n\r\nID\r\n\r\n\r\n\r";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "wit-querygrid-widget-view";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wit-querygrid-widget-view\" id=\"94\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "82";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIQueryreturnednoresulPane
        {
            get
            {
                if ((this.mUIQueryreturnednoresulPane == null))
                {
                    this.mUIQueryreturnednoresulPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIQueryreturnednoresulPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIQueryreturnednoresulPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIQueryreturnednoresulPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Query returned no results. Create new wo";
                    this.mUIQueryreturnednoresulPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIQueryreturnednoresulPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "wit-widget-no-results-message";
                    this.mUIQueryreturnednoresulPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wit-widget-no-results-message\"";
                    this.mUIQueryreturnednoresulPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "111";
                    this.mUIQueryreturnednoresulPane.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIQueryreturnednoresulPane;
            }
        }
        
        public HtmlDiv UIQueryreturnednoresulPane1
        {
            get
            {
                if ((this.mUIQueryreturnednoresulPane1 == null))
                {
                    this.mUIQueryreturnednoresulPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIQueryreturnednoresulPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIQueryreturnednoresulPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIQueryreturnednoresulPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Query returned no results. Create new wo";
                    this.mUIQueryreturnednoresulPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIQueryreturnednoresulPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = "wit-widget-no-results-container";
                    this.mUIQueryreturnednoresulPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wit-widget-no-results-container\" style=\"display: block;\"";
                    this.mUIQueryreturnednoresulPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "110";
                    this.mUIQueryreturnednoresulPane1.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIQueryreturnednoresulPane1;
            }
        }
        
        public HtmlImage UI_statictfs20160204T1Image
        {
            get
            {
                if ((this.mUI_statictfs20160204T1Image == null))
                {
                    this.mUI_statictfs20160204T1Image = new HtmlImage(this);
                    #region Search Criteria
                    this.mUI_statictfs20160204T1Image.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUI_statictfs20160204T1Image.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUI_statictfs20160204T1Image.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUI_statictfs20160204T1Image.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/_static/tfs/20160204T180102/_content/chart-noresult-3.png";
                    this.mUI_statictfs20160204T1Image.FilterProperties[HtmlImage.PropertyNames.Src] = "https://almrangers-sandbox-one.visualstudio.com/_static/tfs/20160204T180102/_cont" +
                        "ent/chart-noresult-3.png";
                    this.mUI_statictfs20160204T1Image.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUI_statictfs20160204T1Image.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "src=\"/_static/tfs/20160204T180102/_conte";
                    this.mUI_statictfs20160204T1Image.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUI_statictfs20160204T1Image.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUI_statictfs20160204T1Image;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIQueryreturnednoresulPane;
        
        private HtmlDiv mUIQueryreturnednoresulPane1;
        
        private HtmlImage mUI_statictfs20160204T1Image;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWidgetscontainerPane : HtmlDiv
    {
        
        public UIWidgetscontainerPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "widgets-container";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Welcome\r\n\r\nGet started using Visual Stud";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "gridster ready";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"gridster ready\" id=\"widgets-container\" style=\"display: block;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "55";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIWelcomeGetstartedusiPane
        {
            get
            {
                if ((this.mUIWelcomeGetstartedusiPane == null))
                {
                    this.mUIWelcomeGetstartedusiPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIWelcomeGetstartedusiPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIWelcomeGetstartedusiPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIWelcomeGetstartedusiPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Welcome\r\n\r\nGet started using Visual Stud";
                    this.mUIWelcomeGetstartedusiPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIWelcomeGetstartedusiPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "gridster-items";
                    this.mUIWelcomeGetstartedusiPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"gridster-items\" style=\"width: 1530px; height: 510px; position: relative;\"";
                    this.mUIWelcomeGetstartedusiPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "57";
                    this.mUIWelcomeGetstartedusiPane.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIWelcomeGetstartedusiPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIWelcomeGetstartedusiPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIExternalContentHost8Frame : HtmlIFrame
    {
        
        public UIExternalContentHost8Frame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "externalContentHost85";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = "externalContentHost85";
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = @"/_apis/public/gallery/publisher/mskold/extension/INT-SampleDataWidget/0.1.0.25/privateasset/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwbiI6Im1za29sZCIsImVuIjoiSU5ULVNhbXBsZURhdGFXaWRnZXQiLCJleHAiOiIxNDU1MjE5NjU3In0=.eGkrRFB3blcxZnQ2VHhTZWFKU0VWeXFxUXNGSlJOcnFmdkRrMmUrMlh4az0=/index.html";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = @"https://mskold.gallery.vsassets.io/_apis/public/gallery/publisher/mskold/extension/INT-SampleDataWidget/0.1.0.25/privateasset/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwbiI6Im1za29sZCIsImVuIjoiSU5ULVNhbXBsZURhdGFXaWRnZXQiLCJleHAiOiIxNDU1MjE5NjU3In0=.eGkrRFB3blcxZnQ2VHhTZWFKU0VWeXFxUXNGSlJOcnFmdkRrMmUrMlh4az0=/index.html";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = "external-content-iframe";
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "name=\"externalContentHost85\" class=\"exte";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public UISampleDataWidgetDocument UISampleDataWidgetDocument
        {
            get
            {
                if ((this.mUISampleDataWidgetDocument == null))
                {
                    this.mUISampleDataWidgetDocument = new UISampleDataWidgetDocument(this);
                }
                return this.mUISampleDataWidgetDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISampleDataWidgetDocument mUISampleDataWidgetDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISampleDataWidgetDocument : HtmlDocument
    {
        
        public UISampleDataWidgetDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sample Data Widget";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = @"/_apis/public/gallery/publisher/mskold/extension/INT-SampleDataWidget/0.1.0.25/privateasset/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwbiI6Im1za29sZCIsImVuIjoiSU5ULVNhbXBsZURhdGFXaWRnZXQiLCJleHAiOiIxNDU1MjE5NjU3In0=.eGkrRFB3blcxZnQ2VHhTZWFKU0VWeXFxUXNGSlJOcnFmdkRrMmUrMlh4az0=/index.html";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"https://mskold.gallery.vsassets.io/_apis/public/gallery/publisher/mskold/extension/INT-SampleDataWidget/0.1.0.25/privateasset/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwbiI6Im1za29sZCIsImVuIjoiSU5ULVNhbXBsZURhdGFXaWRnZXQiLCJleHAiOiIxNDU1MjE5NjU3In0=.eGkrRFB3blcxZnQ2VHhTZWFKU0VWeXFxUXNGSlJOcnFmdkRrMmUrMlh4az0=/index.html";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public UIItem1Pane UIItem1Pane
        {
            get
            {
                if ((this.mUIItem1Pane == null))
                {
                    this.mUIItem1Pane = new UIItem1Pane(this);
                }
                return this.mUIItem1Pane;
            }
        }
        
        public UIStarWarsAnishaDesignPane UIStarWarsAnishaDesignPane
        {
            get
            {
                if ((this.mUIStarWarsAnishaDesignPane == null))
                {
                    this.mUIStarWarsAnishaDesignPane = new UIStarWarsAnishaDesignPane(this);
                }
                return this.mUIStarWarsAnishaDesignPane;
            }
        }
        
        public HtmlInputButton UIPopulateButton
        {
            get
            {
                if ((this.mUIPopulateButton == null))
                {
                    this.mUIPopulateButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIPopulateButton.SearchProperties[HtmlButton.PropertyNames.Id] = "Create";
                    this.mUIPopulateButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIPopulateButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Populate";
                    this.mUIPopulateButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIPopulateButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Create demo data";
                    this.mUIPopulateButton.FilterProperties[HtmlButton.PropertyNames.Class] = "SampleActionButton";
                    this.mUIPopulateButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "title=\"Create demo data\" class=\"SampleAc";
                    this.mUIPopulateButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIPopulateButton.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIPopulateButton;
            }
        }
        
        public HtmlImage UIIconsjonathanreystarImage
        {
            get
            {
                if ((this.mUIIconsjonathanreystarImage == null))
                {
                    this.mUIIconsjonathanreystarImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIIconsjonathanreystarImage.SearchProperties[HtmlImage.PropertyNames.Id] = "TemplateIcon";
                    this.mUIIconsjonathanreystarImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIIconsjonathanreystarImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIIconsjonathanreystarImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/icons/jonathan-rey/star-wars-characters/64/Yoda-01-icon.png";
                    this.mUIIconsjonathanreystarImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://icons.iconarchive.com/icons/jonathan-rey/star-wars-characters/64/Yoda-01-i" +
                        "con.png";
                    this.mUIIconsjonathanreystarImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIIconsjonathanreystarImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "id=\"TemplateIcon\" style=\"float: left;\" s";
                    this.mUIIconsjonathanreystarImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIIconsjonathanreystarImage.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIIconsjonathanreystarImage;
            }
        }
        
        public HtmlInputButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Id] = "Delete";
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Delete";
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Delete demo data";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.Class] = "SampleActionButton";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "title=\"Delete demo data\" class=\"SampleAc";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIDeleteButton.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIDeleteButton;
            }
        }
        
        public UIProgressBarPane UIProgressBarPane
        {
            get
            {
                if ((this.mUIProgressBarPane == null))
                {
                    this.mUIProgressBarPane = new UIProgressBarPane(this);
                }
                return this.mUIProgressBarPane;
            }
        }
        #endregion
        
        #region Fields
        private UIItem1Pane mUIItem1Pane;
        
        private UIStarWarsAnishaDesignPane mUIStarWarsAnishaDesignPane;
        
        private HtmlInputButton mUIPopulateButton;
        
        private HtmlImage mUIIconsjonathanreystarImage;
        
        private HtmlInputButton mUIDeleteButton;
        
        private UIProgressBarPane mUIProgressBarPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem1Pane : HtmlDiv
    {
        
        public UIItem1Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "1";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "combo input-text-box list drop";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"combo input-text-box list drop\" id=\"1\" style=\"width: 100%;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "8";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "drop bowtie-icon bowtie-triangle-down";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"drop bowtie-icon bowtie-triangle-down\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "10";
                    this.mUIItemPane.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStarWarsAnishaDesignPane : HtmlDiv
    {
        
        public UIStarWarsAnishaDesignPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
         
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "combo-drop-popup virtualizing-list-view";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"combo-drop-popup virtualizing-list-view\" id=\"2\" style=\"left: 10px; top: 77" +
                "px; width: 310px; height: 46px; z-index: 20000;\"";
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIStarWarsCustom
        {
            get
            {
                if ((this.mUIStarWarsCustom == null))
                {
                    this.mUIStarWarsCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIStarWarsCustom.SearchProperties["TagName"] = "LI";
                    this.mUIStarWarsCustom.FilterProperties["InnerText"] = "StarWars";
                    #endregion
                }
                return this.mUIStarWarsCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIStarWarsCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIProgressBarPane : HtmlDiv
    {
        
        public UIProgressBarPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ProgressBar";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ProgessBar";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ProgessBar\" id=\"ProgressBar\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "13";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIWorkItemSampleDataSePane
        {
            get
            {
                if ((this.mUIWorkItemSampleDataSePane == null))
                {
                    this.mUIWorkItemSampleDataSePane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIWorkItemSampleDataSePane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIWorkItemSampleDataSePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIWorkItemSampleDataSePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIWorkItemSampleDataSePane.FilterProperties[HtmlDiv.PropertyNames.Title] = "WorkItemSampleDataServiceTFS.WebApi.Exception: TF400898: An Internal Error Occurr" +
                        "ed. Activity Id: 88cd160e-998c-413c-a0e2-7de9cac79205.";
                    this.mUIWorkItemSampleDataSePane.FilterProperties[HtmlDiv.PropertyNames.Class] = "ProgressTask TaskStatusFailed";
                    this.mUIWorkItemSampleDataSePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "title=\"WorkItemSampleDataServiceTFS.WebApi.Exception: TF400898: An Internal Error" +
                        " Occurred. Activity Id: 88cd160e-998c-413c-a0e2-7de9cac79205.\" class=\"ProgressTa" +
                        "sk TaskStatusFailed\" style=\"width: 44.28px;\"";
                    this.mUIWorkItemSampleDataSePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "19";
                    this.mUIWorkItemSampleDataSePane.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIWorkItemSampleDataSePane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIWorkItemSampleDataSePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem97Pane : HtmlDiv
    {
        
        public UIItem97Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "97";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Continuously integrate\r\n\r\nAutomate your ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "how-to-link how-to-link-build";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"how-to-link how-to-link-build\" id=\"97\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "70";
            this.WindowTitles.Add("Overview - Visual Studio Team Services");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIContinuouslyintegratHyperlink
        {
            get
            {
                if ((this.mUIContinuouslyintegratHyperlink == null))
                {
                    this.mUIContinuouslyintegratHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIContinuouslyintegratHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIContinuouslyintegratHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIContinuouslyintegratHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUIContinuouslyintegratHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Continuously integrate\r\n\r\nAutomate your builds";
                    this.mUIContinuouslyintegratHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIContinuouslyintegratHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIContinuouslyintegratHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "/DefaultCollection/SampleDataTest1/_build";
                    this.mUIContinuouslyintegratHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "how-to-link-anchor";
                    this.mUIContinuouslyintegratHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"how-to-link-anchor\" href=\"/Defaul";
                    this.mUIContinuouslyintegratHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIContinuouslyintegratHyperlink.WindowTitles.Add("Overview - Visual Studio Team Services");
                    #endregion
                }
                return this.mUIContinuouslyintegratHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIContinuouslyintegratHyperlink;
        #endregion
    }
}
